# Generated by Django 4.1.3 on 2022-11-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='url',
        ),
        migrations.AddField(
            model_name='map',
            name='url_code',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
