# Generated by Django 4.1.3 on 2022-11-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_map_url_map_url_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geospatial_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('geospatial_data', models.JSONField()),
                ('maps', models.ManyToManyField(related_name='data_sets', to='map.map')),
            ],
        ),
    ]
