# Generated by Django 4.1.3 on 2022-11-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_geospatial_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Geospatial_Data',
            new_name='GeospatialData',
        ),
    ]
