# Generated by Django 4.1.3 on 2022-12-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_geospatialdata_data_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geospatialdata',
            name='data_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='geospatialdata',
            name='geospatial_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geospatialdata',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='title',
            field=models.CharField(max_length=127),
        ),
    ]
