# Generated by Django 4.1.3 on 2022-12-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_geospatialdata_data_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geospatialdata',
            name='title',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
