# Generated by Django 4.1.3 on 2022-12-09 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_renderer_delete_datadisplaysettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renderer',
            old_name='linked_data',
            new_name='linked_data_id',
        ),
        migrations.RenameField(
            model_name='renderer',
            old_name='linked_map',
            new_name='linked_map_id',
        ),
    ]
