# Generated by Django 4.1.7 on 2023-03-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_rename_linked_data_renderer_linked_data_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='default_view',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
